trigger: none
pr:
  - main

variables:
  - group: elarande-general-params

resources:
  repositories:
    - repository: stratus-templates
      type: git
      name: Cloud Excellence Team/stratus-templates
      ref: main

pool:
  vmImage: "ubuntu-latest"

extends:
  template: templates/security/security-scans.yml@stratus-templates
  parameters:
    break: false
    jobs:
    - job: test
      displayName: 'Test'
      steps:
      - template: /templates/test/npm.yml@stratus-templates
        parameters:
          nodeVersion: "20"