trigger: none
pr:
  - main

parameters:
- name: imageTag
  type: string
  displayName: New image tag in production

variables:
  - group: elarande-general-params
  - name: imageName
    value: canvas-kth-sandboxes
  - name: parametersFileName
    value: prod.parameters.json

resources:
  repositories:
    - repository: stratus-templates
      type: git
      name: Cloud Excellence Team/stratus-templates
      ref: main

pool:
  vmImage: "ubuntu-latest"

extends:
  template: templates/security/security-scans.yml@stratus-templates
  parameters:
    break: false
    jobs:
    - job: test
      displayName: 'Test'
      steps:
      - template: /templates/test/npm.yml@stratus-templates
